apiVersion: v1
kind: Service
metadata:
  name: {{ include "customerside.fullname" . }}-cardinal-collector
  labels:
    app.kubernetes.io/component: collector
  {{- include "customerside.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cardinalCollector.type }}
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-{{ .Values.kubernetesClusterName }}-customerside
    app.kubernetes.io/name: cardinalhq
  {{- include "customerside.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.cardinalCollector.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "customerside.fullname" . }}-l2
  labels:
    app.kubernetes.io/component: collector
  {{- include "customerside.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-{{ .Values.kubernetesClusterName }}-customerside
    app.kubernetes.io/name: cardinalhq
  {{- include "customerside.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp2
      port: 14317
      targetPort: 0