project_name: cardinalhq-otel-collector
version: 2
builds:
  - id: cardinalhq-otel-collector
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - s390x
    dir: bin
    binary: cardinalhq-otel-collector
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
release:
  disable: true
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-amd64
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-arm64
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: s390x
    dockerfile: Dockerfile
    image_templates:
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-s390x
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-s390x
    build_flag_templates:
      - --pull
      - --platform=linux/s390x
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
docker_manifests:
  - name_template: public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}
    image_templates:
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-amd64
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-arm64
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-s390x
  - name_template: public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest
    image_templates:
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-amd64
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-arm64
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-s390x
