project_name: cardinalhq-otel-collector
version: 2
builds:
  - id: cardinalhq-otel-collector
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    dir: distribution
    binary: cardinalhq-otel-collector
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
release:
  disable: true
changelog:
  disable: true
archives:
  - id: default
    # use the "binary" format so GoReleaser skips creating an archive
    formats:
      - binary
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    extra_files:
      - docker/
    image_templates:
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-amd64
      # - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-dev-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    push_flags:
      - --provenance=false
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    extra_files:
      - docker/
    image_templates:
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-arm64
      # - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-dev-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    push_flags:
      - --provenance=false
    use: buildx
docker_manifests:
  - name_template: public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}
    image_templates:
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-amd64
      - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:v{{ .Version }}-arm64
  # - name_template: public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-dev
  #   image_templates:
  #     - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-dev-amd64
  #     - public.ecr.aws/cardinalhq.io/cardinalhq-otel-collector:latest-dev-arm64
