header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CardinalHQ, Inc

  paths-ignore:
    - 'bin'
    - 'buildtime'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - .gitignore
    - .dockerignore
    - .github
    - .licenserc.yaml
    - '**/*.yaml'
    - go.sum
    - go.mod
    - sample-config.yaml
    - '**/testdata/**'
    - .idea

  comment: on-failure

  language:
    rl:
      extensions:
        - '.rl'
      comment_style_id: DoubleSlash

# If you don't want to check dependencies' license compatibility, remove the following part
dependency:
  files:
    - go.mod
