// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: metrics.proto

package ddpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricPayload_MetricType int32

const (
	MetricPayload_UNSPECIFIED MetricPayload_MetricType = 0
	MetricPayload_COUNT       MetricPayload_MetricType = 1
	MetricPayload_RATE        MetricPayload_MetricType = 2
	MetricPayload_GAUGE       MetricPayload_MetricType = 3
)

// Enum value maps for MetricPayload_MetricType.
var (
	MetricPayload_MetricType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "COUNT",
		2: "RATE",
		3: "GAUGE",
	}
	MetricPayload_MetricType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"COUNT":       1,
		"RATE":        2,
		"GAUGE":       3,
	}
)

func (x MetricPayload_MetricType) Enum() *MetricPayload_MetricType {
	p := new(MetricPayload_MetricType)
	*p = x
	return p
}

func (x MetricPayload_MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricPayload_MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricPayload_MetricType) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[0]
}

func (x MetricPayload_MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricPayload_MetricType.Descriptor instead.
func (MetricPayload_MetricType) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3, 0}
}

type CommonMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CurrentEpoch  float64                `protobuf:"fixed64,3,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	InternalIp    string                 `protobuf:"bytes,4,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	PublicIp      string                 `protobuf:"bytes,5,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	ApiKey        string                 `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonMetadata) Reset() {
	*x = CommonMetadata{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonMetadata) ProtoMessage() {}

func (x *CommonMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonMetadata.ProtoReflect.Descriptor instead.
func (*CommonMetadata) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *CommonMetadata) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *CommonMetadata) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CommonMetadata) GetCurrentEpoch() float64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *CommonMetadata) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *CommonMetadata) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *CommonMetadata) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type Origin struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginProduct  uint32                 `protobuf:"varint,4,opt,name=origin_product,json=originProduct,proto3" json:"origin_product,omitempty"`
	OriginCategory uint32                 `protobuf:"varint,5,opt,name=origin_category,json=originCategory,proto3" json:"origin_category,omitempty"`
	OriginService  uint32                 `protobuf:"varint,6,opt,name=origin_service,json=originService,proto3" json:"origin_service,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Origin) Reset() {
	*x = Origin{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Origin) ProtoMessage() {}

func (x *Origin) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Origin.ProtoReflect.Descriptor instead.
func (*Origin) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Origin) GetOriginProduct() uint32 {
	if x != nil {
		return x.OriginProduct
	}
	return 0
}

func (x *Origin) GetOriginCategory() uint32 {
	if x != nil {
		return x.OriginCategory
	}
	return 0
}

func (x *Origin) GetOriginService() uint32 {
	if x != nil {
		return x.OriginService
	}
	return 0
}

// Metadata is used in both the MetricSeries and Sketch messages defined below.
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        *Origin                `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetOrigin() *Origin {
	if x != nil {
		return x.Origin
	}
	return nil
}

type MetricPayload struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Series        []*MetricPayload_MetricSeries `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPayload) Reset() {
	*x = MetricPayload{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload) ProtoMessage() {}

func (x *MetricPayload) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload.ProtoReflect.Descriptor instead.
func (*MetricPayload) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *MetricPayload) GetSeries() []*MetricPayload_MetricSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

type EventsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventsPayload_Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Metadata      *CommonMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsPayload) Reset() {
	*x = EventsPayload{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsPayload) ProtoMessage() {}

func (x *EventsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsPayload.ProtoReflect.Descriptor instead.
func (*EventsPayload) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *EventsPayload) GetEvents() []*EventsPayload_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventsPayload) GetMetadata() *CommonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SketchPayload struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Sketches      []*SketchPayload_Sketch `protobuf:"bytes,1,rep,name=sketches,proto3" json:"sketches,omitempty"` // [(gogoproto.nullable) = false];
	Metadata      *CommonMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"` // [(gogoproto.nullable) = false];
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchPayload) Reset() {
	*x = SketchPayload{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchPayload) ProtoMessage() {}

func (x *SketchPayload) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchPayload.ProtoReflect.Descriptor instead.
func (*SketchPayload) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *SketchPayload) GetSketches() []*SketchPayload_Sketch {
	if x != nil {
		return x.Sketches
	}
	return nil
}

func (x *SketchPayload) GetMetadata() *CommonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetricPayload_MetricPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// metric value
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// timestamp for this value in seconds since the UNIX epoch
	Timestamp     int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPayload_MetricPoint) Reset() {
	*x = MetricPayload_MetricPoint{}
	mi := &file_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload_MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload_MetricPoint) ProtoMessage() {}

func (x *MetricPayload_MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload_MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPayload_MetricPoint) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3, 0}
}

func (x *MetricPayload_MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPayload_MetricPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MetricPayload_Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPayload_Resource) Reset() {
	*x = MetricPayload_Resource{}
	mi := &file_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload_Resource) ProtoMessage() {}

func (x *MetricPayload_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload_Resource.ProtoReflect.Descriptor instead.
func (*MetricPayload_Resource) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3, 1}
}

func (x *MetricPayload_Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricPayload_Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MetricPayload_MetricSeries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resources this series applies to; include at least
	// { type="host", name=<hostname> }
	Resources []*MetricPayload_Resource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	// metric name
	Metric string `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	// tags for this metric
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// data points for this metric
	Points []*MetricPayload_MetricPoint `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	// type of metric
	Type MetricPayload_MetricType `protobuf:"varint,5,opt,name=type,proto3,enum=ddpb.MetricPayload_MetricType" json:"type,omitempty"`
	// metric unit name
	Unit string `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	// source of this metric (check name, etc.)
	SourceTypeName string `protobuf:"bytes,7,opt,name=source_type_name,json=sourceTypeName,proto3" json:"source_type_name,omitempty"`
	// interval, in seconds, between samples of this metric
	Interval int64 `protobuf:"varint,8,opt,name=interval,proto3" json:"interval,omitempty"`
	// Metrics origin metadata
	Metadata      *Metadata `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPayload_MetricSeries) Reset() {
	*x = MetricPayload_MetricSeries{}
	mi := &file_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload_MetricSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload_MetricSeries) ProtoMessage() {}

func (x *MetricPayload_MetricSeries) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload_MetricSeries.ProtoReflect.Descriptor instead.
func (*MetricPayload_MetricSeries) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3, 2}
}

func (x *MetricPayload_MetricSeries) GetResources() []*MetricPayload_Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *MetricPayload_MetricSeries) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricPayload_MetricSeries) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MetricPayload_MetricSeries) GetPoints() []*MetricPayload_MetricPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *MetricPayload_MetricSeries) GetType() MetricPayload_MetricType {
	if x != nil {
		return x.Type
	}
	return MetricPayload_UNSPECIFIED
}

func (x *MetricPayload_MetricSeries) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricPayload_MetricSeries) GetSourceTypeName() string {
	if x != nil {
		return x.SourceTypeName
	}
	return ""
}

func (x *MetricPayload_MetricSeries) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *MetricPayload_MetricSeries) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EventsPayload_Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Ts             int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Priority       string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Host           string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Tags           []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	AlertType      string                 `protobuf:"bytes,7,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"`
	AggregationKey string                 `protobuf:"bytes,8,opt,name=aggregation_key,json=aggregationKey,proto3" json:"aggregation_key,omitempty"`
	SourceTypeName string                 `protobuf:"bytes,9,opt,name=source_type_name,json=sourceTypeName,proto3" json:"source_type_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventsPayload_Event) Reset() {
	*x = EventsPayload_Event{}
	mi := &file_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsPayload_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsPayload_Event) ProtoMessage() {}

func (x *EventsPayload_Event) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsPayload_Event.ProtoReflect.Descriptor instead.
func (*EventsPayload_Event) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4, 0}
}

func (x *EventsPayload_Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventsPayload_Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EventsPayload_Event) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *EventsPayload_Event) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *EventsPayload_Event) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EventsPayload_Event) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventsPayload_Event) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *EventsPayload_Event) GetAggregationKey() string {
	if x != nil {
		return x.AggregationKey
	}
	return ""
}

func (x *EventsPayload_Event) GetSourceTypeName() string {
	if x != nil {
		return x.SourceTypeName
	}
	return ""
}

type SketchPayload_Sketch struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Metric        string                               `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Host          string                               `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Distributions []*SketchPayload_Sketch_Distribution `protobuf:"bytes,3,rep,name=distributions,proto3" json:"distributions,omitempty"` // [(gogoproto.nullable) = false];
	Tags          []string                             `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Dogsketches   []*SketchPayload_Sketch_Dogsketch    `protobuf:"bytes,7,rep,name=dogsketches,proto3" json:"dogsketches,omitempty"` // [(gogoproto.nullable) = false];
	Metadata      *Metadata                            `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchPayload_Sketch) Reset() {
	*x = SketchPayload_Sketch{}
	mi := &file_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchPayload_Sketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchPayload_Sketch) ProtoMessage() {}

func (x *SketchPayload_Sketch) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchPayload_Sketch.ProtoReflect.Descriptor instead.
func (*SketchPayload_Sketch) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SketchPayload_Sketch) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SketchPayload_Sketch) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SketchPayload_Sketch) GetDistributions() []*SketchPayload_Sketch_Distribution {
	if x != nil {
		return x.Distributions
	}
	return nil
}

func (x *SketchPayload_Sketch) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SketchPayload_Sketch) GetDogsketches() []*SketchPayload_Sketch_Dogsketch {
	if x != nil {
		return x.Dogsketches
	}
	return nil
}

func (x *SketchPayload_Sketch) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SketchPayload_Sketch_Distribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Cnt           int64                  `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Min           float64                `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	Avg           float64                `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	Sum           float64                `protobuf:"fixed64,6,opt,name=sum,proto3" json:"sum,omitempty"`
	V             []float64              `protobuf:"fixed64,7,rep,packed,name=v,proto3" json:"v,omitempty"`
	G             []uint32               `protobuf:"varint,8,rep,packed,name=g,proto3" json:"g,omitempty"`
	Delta         []uint32               `protobuf:"varint,9,rep,packed,name=delta,proto3" json:"delta,omitempty"`
	Buf           []float64              `protobuf:"fixed64,10,rep,packed,name=buf,proto3" json:"buf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchPayload_Sketch_Distribution) Reset() {
	*x = SketchPayload_Sketch_Distribution{}
	mi := &file_metrics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchPayload_Sketch_Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchPayload_Sketch_Distribution) ProtoMessage() {}

func (x *SketchPayload_Sketch_Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchPayload_Sketch_Distribution.ProtoReflect.Descriptor instead.
func (*SketchPayload_Sketch_Distribution) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *SketchPayload_Sketch_Distribution) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetCnt() int64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetV() []float64 {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *SketchPayload_Sketch_Distribution) GetG() []uint32 {
	if x != nil {
		return x.G
	}
	return nil
}

func (x *SketchPayload_Sketch_Distribution) GetDelta() []uint32 {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *SketchPayload_Sketch_Distribution) GetBuf() []float64 {
	if x != nil {
		return x.Buf
	}
	return nil
}

type SketchPayload_Sketch_Dogsketch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Cnt           int64                  `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Min           float64                `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	Avg           float64                `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	Sum           float64                `protobuf:"fixed64,6,opt,name=sum,proto3" json:"sum,omitempty"`
	K             []int32                `protobuf:"zigzag32,7,rep,packed,name=k,proto3" json:"k,omitempty"`
	N             []uint32               `protobuf:"varint,8,rep,packed,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchPayload_Sketch_Dogsketch) Reset() {
	*x = SketchPayload_Sketch_Dogsketch{}
	mi := &file_metrics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchPayload_Sketch_Dogsketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchPayload_Sketch_Dogsketch) ProtoMessage() {}

func (x *SketchPayload_Sketch_Dogsketch) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchPayload_Sketch_Dogsketch.ProtoReflect.Descriptor instead.
func (*SketchPayload_Sketch_Dogsketch) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5, 0, 1}
}

func (x *SketchPayload_Sketch_Dogsketch) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetCnt() int64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetK() []int32 {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *SketchPayload_Sketch_Dogsketch) GetN() []uint32 {
	if x != nil {
		return x.N
	}
	return nil
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\x04ddpb\"\xcd\x01\n" +
	"\x0eCommonMetadata\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x12#\n" +
	"\rcurrent_epoch\x18\x03 \x01(\x01R\fcurrentEpoch\x12\x1f\n" +
	"\vinternal_ip\x18\x04 \x01(\tR\n" +
	"internalIp\x12\x1b\n" +
	"\tpublic_ip\x18\x05 \x01(\tR\bpublicIp\x12\x17\n" +
	"\aapi_key\x18\x06 \x01(\tR\x06apiKey\"\x91\x01\n" +
	"\x06Origin\x12%\n" +
	"\x0eorigin_product\x18\x04 \x01(\rR\roriginProduct\x12'\n" +
	"\x0forigin_category\x18\x05 \x01(\rR\x0eoriginCategory\x12%\n" +
	"\x0eorigin_service\x18\x06 \x01(\rR\roriginServiceJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"0\n" +
	"\bMetadata\x12$\n" +
	"\x06origin\x18\x01 \x01(\v2\f.ddpb.OriginR\x06origin\"\xeb\x04\n" +
	"\rMetricPayload\x128\n" +
	"\x06series\x18\x01 \x03(\v2 .ddpb.MetricPayload.MetricSeriesR\x06series\x1aA\n" +
	"\vMetricPoint\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x1a2\n" +
	"\bResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a\xe9\x02\n" +
	"\fMetricSeries\x12:\n" +
	"\tresources\x18\x01 \x03(\v2\x1c.ddpb.MetricPayload.ResourceR\tresources\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x127\n" +
	"\x06points\x18\x04 \x03(\v2\x1f.ddpb.MetricPayload.MetricPointR\x06points\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.ddpb.MetricPayload.MetricTypeR\x04type\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12(\n" +
	"\x10source_type_name\x18\a \x01(\tR\x0esourceTypeName\x12\x1a\n" +
	"\binterval\x18\b \x01(\x03R\binterval\x12*\n" +
	"\bmetadata\x18\t \x01(\v2\x0e.ddpb.MetadataR\bmetadata\"=\n" +
	"\n" +
	"MetricType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05COUNT\x10\x01\x12\b\n" +
	"\x04RATE\x10\x02\x12\t\n" +
	"\x05GAUGE\x10\x03\"\xee\x02\n" +
	"\rEventsPayload\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.ddpb.EventsPayload.EventR\x06events\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.ddpb.CommonMetadataR\bmetadata\x1a\xf7\x01\n" +
	"\x05Event\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"alert_type\x18\a \x01(\tR\talertType\x12'\n" +
	"\x0faggregation_key\x18\b \x01(\tR\x0eaggregationKey\x12(\n" +
	"\x10source_type_name\x18\t \x01(\tR\x0esourceTypeName\"\x86\x06\n" +
	"\rSketchPayload\x126\n" +
	"\bsketches\x18\x01 \x03(\v2\x1a.ddpb.SketchPayload.SketchR\bsketches\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.ddpb.CommonMetadataR\bmetadata\x1a\x8a\x05\n" +
	"\x06Sketch\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12M\n" +
	"\rdistributions\x18\x03 \x03(\v2'.ddpb.SketchPayload.Sketch.DistributionR\rdistributions\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12F\n" +
	"\vdogsketches\x18\a \x03(\v2$.ddpb.SketchPayload.Sketch.DogsketchR\vdogsketches\x12*\n" +
	"\bmetadata\x18\b \x01(\v2\x0e.ddpb.MetadataR\bmetadata\x1a\xbc\x01\n" +
	"\fDistribution\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x10\n" +
	"\x03cnt\x18\x02 \x01(\x03R\x03cnt\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x01R\x03max\x12\x10\n" +
	"\x03avg\x18\x05 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03sum\x18\x06 \x01(\x01R\x03sum\x12\f\n" +
	"\x01v\x18\a \x03(\x01R\x01v\x12\f\n" +
	"\x01g\x18\b \x03(\rR\x01g\x12\x14\n" +
	"\x05delta\x18\t \x03(\rR\x05delta\x12\x10\n" +
	"\x03buf\x18\n" +
	" \x03(\x01R\x03buf\x1a\x91\x01\n" +
	"\tDogsketch\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x10\n" +
	"\x03cnt\x18\x02 \x01(\x03R\x03cnt\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x01R\x03max\x12\x10\n" +
	"\x03avg\x18\x05 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03sum\x18\x06 \x01(\x01R\x03sum\x12\f\n" +
	"\x01k\x18\a \x03(\x11R\x01k\x12\f\n" +
	"\x01n\x18\b \x03(\rR\x01nJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aR\x0edistributionsKR\x0edistributionsCB\bZ\x06.;ddpbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_metrics_proto_goTypes = []any{
	(MetricPayload_MetricType)(0),             // 0: ddpb.MetricPayload.MetricType
	(*CommonMetadata)(nil),                    // 1: ddpb.CommonMetadata
	(*Origin)(nil),                            // 2: ddpb.Origin
	(*Metadata)(nil),                          // 3: ddpb.Metadata
	(*MetricPayload)(nil),                     // 4: ddpb.MetricPayload
	(*EventsPayload)(nil),                     // 5: ddpb.EventsPayload
	(*SketchPayload)(nil),                     // 6: ddpb.SketchPayload
	(*MetricPayload_MetricPoint)(nil),         // 7: ddpb.MetricPayload.MetricPoint
	(*MetricPayload_Resource)(nil),            // 8: ddpb.MetricPayload.Resource
	(*MetricPayload_MetricSeries)(nil),        // 9: ddpb.MetricPayload.MetricSeries
	(*EventsPayload_Event)(nil),               // 10: ddpb.EventsPayload.Event
	(*SketchPayload_Sketch)(nil),              // 11: ddpb.SketchPayload.Sketch
	(*SketchPayload_Sketch_Distribution)(nil), // 12: ddpb.SketchPayload.Sketch.Distribution
	(*SketchPayload_Sketch_Dogsketch)(nil),    // 13: ddpb.SketchPayload.Sketch.Dogsketch
}
var file_metrics_proto_depIdxs = []int32{
	2,  // 0: ddpb.Metadata.origin:type_name -> ddpb.Origin
	9,  // 1: ddpb.MetricPayload.series:type_name -> ddpb.MetricPayload.MetricSeries
	10, // 2: ddpb.EventsPayload.events:type_name -> ddpb.EventsPayload.Event
	1,  // 3: ddpb.EventsPayload.metadata:type_name -> ddpb.CommonMetadata
	11, // 4: ddpb.SketchPayload.sketches:type_name -> ddpb.SketchPayload.Sketch
	1,  // 5: ddpb.SketchPayload.metadata:type_name -> ddpb.CommonMetadata
	8,  // 6: ddpb.MetricPayload.MetricSeries.resources:type_name -> ddpb.MetricPayload.Resource
	7,  // 7: ddpb.MetricPayload.MetricSeries.points:type_name -> ddpb.MetricPayload.MetricPoint
	0,  // 8: ddpb.MetricPayload.MetricSeries.type:type_name -> ddpb.MetricPayload.MetricType
	3,  // 9: ddpb.MetricPayload.MetricSeries.metadata:type_name -> ddpb.Metadata
	12, // 10: ddpb.SketchPayload.Sketch.distributions:type_name -> ddpb.SketchPayload.Sketch.Distribution
	13, // 11: ddpb.SketchPayload.Sketch.dogsketches:type_name -> ddpb.SketchPayload.Sketch.Dogsketch
	3,  // 12: ddpb.SketchPayload.Sketch.metadata:type_name -> ddpb.Metadata
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		EnumInfos:         file_metrics_proto_enumTypes,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
