// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("chqprw")
	ScopeName = "github.com/cardinalhq/cardinalhq-otel-collector/receiver/chqprwreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
