apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "customerside.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector-l2
  {{- include "customerside.configMap.annotations" . | nindent 2 }}
  name: {{ include "customerside.fullname" . }}-collector-config-l2
  {{- include "customerside.namespace" . | nindent 2 }}
data:
  config.yaml: |-
    receivers:
      otlp/l2:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.collector.ports.internal.otlpGRPCPort}}

    exporters:
      nop:
      chqdatadog/datadog:
        api_key: ${env:DATADOG_API_KEY}
        metrics:
          endpoint: {{ .Values.collector.endpoints.datadog.metrics }}
          compression: {{ .Values.collector.endpoints.datadog.compression }}
        logs:
          endpoint: {{ .Values.collector.endpoints.datadog.logs }}
          compression: {{ .Values.collector.endpoints.datadog.compression }}
        traces:
          endpoint: {{ .Values.collector.endpoints.datadog.traces }}
          compression: {{ .Values.collector.endpoints.datadog.compression }}

      otlp/cardinalhq:
        endpoint: {{ .Values.collector.endpoints.cardinalhq.otlpGRPC}}
        auth:
          authenticator: chqauth/cardinalhq

    processors:
      # Limit collector process memory usage.  This should be the first processor
      # in the processor list.
      memory_limiter/l2:
        limit_mib: 750
        spike_limit_mib: 100
        check_interval: 5s

      batch/cardinalhq:
        timeout: 1s
        send_batch_size: 100
        send_batch_max_size: 1000
      batch/datadog:
        timeout: 1s
        send_batch_size: 100
        send_batch_max_size: 1000
      batch/intakestats:
        timeout: 1s
        send_batch_size: 100
        send_batch_max_size: 1000
      
      groupbytrace/l2:
        wait_duration: 60s

      cumulativetodelta/l2:

      chqdecorator/l2:
        traces:
          uninteresting_rate: 1000
          has_error_rate: 4

      chqenforcer/intakestats:
        configuration_extension: chqconfig/cardinalhq
        drop_decoration_attributes: false
        statistics:
          endpoint: {{ .Values.collector.endpoints.cardinalhq.stats }}
          phase: presample
          vendor: intakestats

      chqenforcer/cardinalhq:
        configuration_extension: chqconfig/cardinalhq
        drop_decoration_attributes: false
        statistics:
          endpoint: {{ .Values.collector.endpoints.cardinalhq.stats }}
          phase: postsample
          vendor: cardinalhq

      chqenforcer/datadog:
        configuration_extension: chqconfig/cardinalhq
        statistics:
          endpoint: {{ .Values.collector.endpoints.cardinalhq.stats }}
          phase: postsample
          vendor: datadog

    connectors:
      forward/cardinalhq:
      forward/datadog:
      forward/intakestats:
        
    service:
      pipelines:
        metrics/l2:
          receivers: [otlp/l2]
          processors: [memory_limiter/l2, cumulativetodelta/l2, chqdecorator/l2]
          exporters: [forward/intakestats, forward/cardinalhq, forward/datadog]
        metrics/intakestats:
          receivers: [forward/intakestats]
          processors: [chqenforcer/intakestats]
          exporters: [nop]
        metrics/cardinalhq:
          receivers: [forward/cardinalhq]
          processors: [chqenforcer/cardinalhq, batch/cardinalhq]
          exporters: [otlp/cardinalhq]
        metrics/datadog:
          receivers: [forward/datadog]
          processors: [chqenforcer/datadog, batch/datadog]
          exporters: [chqdatadog/datadog]

        traces/l2:
          receivers: [otlp/l2]
          processors: [memory_limiter/l2, groupbytrace/l2, chqdecorator/l2]
          exporters: [forward/intakestats, forward/cardinalhq, forward/datadog]
        traces/intakestats:
          receivers: [forward/intakestats]
          processors: [chqenforcer/intakestats]
          exporters: [nop]
        traces/cardinalhq:
          receivers: [forward/cardinalhq]
          processors: [chqenforcer/cardinalhq, batch/cardinalhq]
          exporters: [otlp/cardinalhq]
        traces/datadog:
          receivers: [forward/datadog]
          processors: [chqenforcer/datadog, batch/datadog]
          exporters: [chqdatadog/datadog]

      {{ toYaml .Values.selfTelemetry | nindent 6 }}

      extensions:
        - zpages
        - health_check
        - chqauth/cardinalhq
        - chqconfig/cardinalhq

    extensions:
      zpages:
        endpoint: "0.0.0.0:{{ .Values.collector.endpoints.zpages.port }}"
      health_check:
        endpoint: "0.0.0.0:{{ .Values.collector.endpoints.healthz.port }}"
        path: {{ .Values.collector.endpoints.healthz.path }}
      chqauth/cardinalhq:
        client_auth:
          api_key: ${env:CARDINALHQ_API_KEY}
      chqconfig/cardinalhq:
        source:
          endpoint: {{ .Values.collector.endpoints.cardinalhq.samplerConfig }}
          auth:
            authenticator: chqauth/cardinalhq
