apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "customerside.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector-l2
  {{- include "customerside.configMap.annotations" . | nindent 2 }}
  name: {{ include "customerside.fullname" . }}-collector-config-l2
  {{- include "customerside.namespace" . | nindent 2 }}
data:
  config.yaml: |-
    receivers:
      otlp/l2:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.collector.ports.internal.otlpGRPCPort}}

    exporters:
      nop:

      {{ range $name, $flags := .Values.vendors }}
      {{ if $flags.enabled -}}
      {{ $flags.exporter }}/{{ $name }}:
        {{ toYaml $flags.config | nindent 8 }}
      {{ end -}}
      {{ end }}

    processors:
      # Limit collector process memory usage.  This should be the first processor
      # in the processor list.
      memory_limiter/l2:
        limit_mib: 750
        spike_limit_mib: 100
        check_interval: 5s

      batch/intakestats:
        timeout: 1s
        send_batch_size: 100
        send_batch_max_size: 1000

      {{ range $name, $flags := .Values.vendors -}}
      {{ if $flags.enabled -}}
      batch/{{ $name }}:
        timeout: 1s
        send_batch_size: 100
        send_batch_max_size: 1000
      {{ end -}}
      {{ end -}}
      
      groupbytrace/l2:
        wait_duration: 60s

      cumulativetodelta/l2:

      chqdecorator/l2:
        traces:
          uninteresting_rate: 1000
          has_error_rate: 4

      chqenforcer/intakestats:
        configuration_extension: chqconfig/cardinalhq
        drop_decoration_attributes: false
        statistics:
          endpoint: {{ .Values.collector.endpoints.cardinalhq.stats }}
          auth:
            authenticator: chqauth/cardinalhq
          phase: presample
          vendor: intakestats

      {{ range $name, $flags := .Values.vendors -}}
      {{ if $flags.enabled -}}
      chqenforcer/{{ $name }}:
        configuration_extension: chqconfig/cardinalhq
        {{ if $flags.keepTags }}
        drop_decoration_attributes: false
        {{ end }}
        statistics:
          endpoint: {{ $.Values.collector.endpoints.cardinalhq.stats }}
          auth:
            authenticator: chqauth/cardinalhq
          phase: postsample
          vendor: {{ $name }}
      {{ end -}}
      {{ end }}

    connectors:
      forward/intakestats:
      {{ range $name, $flags := .Values.vendors -}}
      {{ if $flags.enabled -}}
      forward/{{ $name }}:
      {{ end -}}
      {{ end }}
        
    service:
      pipelines:
        metrics/l2:
          receivers:
            - otlp/l2
          processors:
            - memory_limiter/l2
            - cumulativetodelta/l2
            - chqdecorator/l2
          exporters:
            - forward/intakestats:
            {{ range $name, $flags := .Values.vendors -}}
            {{ if $flags.enabled -}}
            - forward/{{ $name }}:
            {{ end -}}
            {{ end }}
        metrics/intakestats:
          receivers:
            - forward/intakestats
          processors:
            - chqenforcer/intakestats
          exporters:
            - nop
        {{ range $name, $flags := .Values.vendors }}
        {{ if $flags.enabled -}}
        metrics/{{ $name }}:
          receivers:
            - forward/{{ $name }}
          processors:
            - chqenforcer/{{ $name }}
            - batch/{{ $name }}
          exporters:
            - {{ $flags.exporter}}/{{ $name }}
        {{ end -}}
        {{- end -}}

        traces/l2:
          receivers:
            - otlp/l2
          processors:
            - memory_limiter/l2
            - groupbytrace/l2
            - chqdecorator/l2
          exporters:
            - forward/intakestats
            - forward/cardinalhq
            - forward/datadog
        traces/intakestats:
          receivers:
            - forward/intakestats
          processors:
            - chqenforcer/intakestats
          exporters:
            - nop
        traces/cardinalhq:
          receivers:
            - forward/cardinalhq
          processors:
            - chqenforcer/cardinalhq
            - batch/cardinalhq
          exporters:
            - otlp/cardinalhq
        traces/datadog:
          receivers:
            - forward/datadog
          processors:
            - chqenforcer/datadog
            - batch/datadog
          exporters:
            - chqdatadog/datadog

      {{ toYaml .Values.selfTelemetry | nindent 6 }}

      extensions:
        - zpages
        - health_check
        - chqauth/cardinalhq
        - chqconfig/cardinalhq

    extensions:
      zpages:
        endpoint: "0.0.0.0:{{ .Values.collector.endpoints.zpages.port }}"
      health_check:
        endpoint: "0.0.0.0:{{ .Values.collector.endpoints.healthz.port }}"
        path: {{ .Values.collector.endpoints.healthz.path }}
      chqauth/cardinalhq:
        client_auth:
          api_key: ${env:CARDINALHQ_API_KEY}
      chqconfig/cardinalhq:
        source:
          endpoint: {{ .Values.collector.endpoints.cardinalhq.samplerConfig }}
          auth:
            authenticator: chqauth/cardinalhq
