apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "customerside.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector-l2
  {{- include "customerside.configMap.annotations" . | nindent 2 }}
  name: {{ include "customerside.fullname" . }}-collector-config-l2
  {{- include "customerside.namespace" . | nindent 2 }}
data:
  config.yaml: |-
    receivers:
      otlp/l2:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.collector.ports.internal.otlpGRPCPort}}

    exporters:

      # Exporter for sending telemetry CardinalHQ via the Datadog exporters.
      chqdatadog/cardinalhq:
        api_key: ${env:DATADOG_API_KEY}
        metrics:
          endpoint: {{ .Values.collector.endpoints.datadog.metrics }}
          compression: {{ .Values.collector.endpoints.datadog.compression }}
        logs:
          endpoint: {{ .Values.collector.endpoints.datadog.logs }}
          compression: {{ .Values.collector.endpoints.datadog.compression }}
        traces:
          endpoint: {{ .Values.collector.endpoints.datadog.traces }}
          compression: {{ .Values.collector.endpoints.datadog.compression }}

      otlp/tochq:
        endpoint: {{ .Values.collector.endpoints.cardinalHQ.otlpGRPC}}
        headers:
          x-cardinalhq-api-key: "${env:CARDINALHQ_API_KEY}"

      chqstats/cardinalhq:
        endpoint: {{ .Values.collector.endpoints.cardinalHQ.stats }}
        api_key: ${env:CARDINALHQ_API_KEY}
        interval: {{ .Values.collector.endpoints.cardinalHQ.statsInterval }}

    processors:
      # Limit collector process memory usage.  This should be the first processor
      # in the processor list.
      memory_limiter/csl2:
        limit_mib: 750
        spike_limit_mib: 100
        check_interval: 5s

      # Batch processors to limit the size and/or timeframe that telemetry
      # is batched before being sent to the exporters.  This should be
      # the last item in the processor list.
      batch/csl2metrics:
        timeout: 1s
        send_batch_size: 100
        send_batch_max_size: 1000
      batch/csl2traces:
        timeout: 20s
        send_batch_size: 100
        send_batch_max_size: 1000
      
      # Group by trace processor to group trace data by trace ID.
      groupbytrace/csl2:
        wait_duration: 60s

      cumulativetodelta/csl2:

      # This processor should be added to the list of processors before
      # the filter/toprovider, and the exporters that write to S3 or to upstream
      # providers, such as Datadog.  It will add attributes to the telemetry
      # which will allow selectively sending metrics on to the upstream
      # provider.  This markup is also written to S3 for later processing
      # by CardinalHQ.
      chqdecorator/csl2:
        sampler_config_file: {{ .Values.collector.endpoints.cardinalHQ.samplerConfig }}
        api_key: ${env:CARDINALHQ_API_KEY}
        traces:
          uninteresting_rate: 1000
          has_error_rate: 4

      # This processor should be added to the list of processors that
      # are in the pipeline destined to the upstream provider, such as
      # Datadog.  It should NOT be used to filter output to S3 for
      # later processing by CardinalHQ.
      filter/toprovider:
        error_mode: ignore
        logs:
          log_record:
            - 'attributes["_cardinalhq.filtered"] == true'
        metrics:
          datapoint:
            - 'attributes["_cardinalhq.filtered"] == true'
        traces:
          span:
            - 'attributes["_cardinalhq.filtered"] == true'

      # Items marked with _cardinalhq.aggregated_output are not sent to
      # CardinalHQ, as the metrics they represent would already be
      # included in the detailed metrics.
      filter/tochq:
        error_mode: ignore
        logs:
          log_record:
            - 'attributes["_cardinalhq.aggregated_output"] == true'
        metrics:
          datapoint:
            - 'attributes["_cardinalhq.aggregated_output"] == true'
        traces:
          span:
            - 'attributes["_cardinalhq.aggregated_output"] == true'

      # This processor should be added to the list of processors that
      # are in the pipeline destined to the upstream provider, such as
      # Datadog.  It should NOT be used to filter output sent to
      # CardinalHQ.
      attributes/toprovider:
        actions:
          - action: delete
            pattern: '^_cardinalhq.*'

    connectors:
      forward/toprovider:
      forward/tochq:
        
    service:
      pipelines:

        # metric handling.  Partition on metric name so aggregations
        # work properly.  TODO: modify aggregator to add artificial attribute
        # for the host that processed the aggregation, and let the receiver
        # just get more than one time series for our aggregation.
        metrics/decoration:
          receivers: [otlp/l2]
          processors: [memory_limiter/csl2, cumulativetodelta/csl2, chqdecorator/csl2, batch/csl2metrics]
          exporters: [forward/tochq, forward/toprovider, chqstats/cardinalhq]
        metrics/chq:
          receivers: [forward/tochq]
          processors: [filter/tochq]
          exporters: [otlp/tochq]
        metrics/toprovider:
          receivers: [forward/toprovider]
          processors: [filter/toprovider, attributes/toprovider]
          exporters: [chqdatadog/cardinalhq]

        # trace handling.  Partition on trace ID so we can group traces
        # and filter based on the entire trace, not individual spans.
        traces/chq:
          receivers: [otlp/l2]
          processors: [memory_limiter/csl2, groupbytrace/csl2, chqdecorator/csl2, batch/csl2traces]
          exporters: [otlp/tochq, forward/toprovider]
        traces/toprovider:
          receivers: [forward/toprovider]
          processors: [filter/toprovider, attributes/toprovider]
          exporters: [chqdatadog/cardinalhq]

      {{ toYaml .Values.selfTelemetry | nindent 6 }}

      extensions:
        - zpages
        - health_check

    extensions:
      zpages:
        endpoint: "0.0.0.0:{{ .Values.collector.endpoints.zpages.port }}"
      health_check:
        endpoint: "0.0.0.0:{{ .Values.collector.endpoints.healthz.port }}"
        path: {{ .Values.collector.endpoints.healthz.path }}
