apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "customerside.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector-l2
  {{- include "customerside.configMap.annotations" . | nindent 2 }}
  name: {{ include "customerside.fullname" . }}-l2
  {{- include "customerside.namespace" . | nindent 2 }}
data:
  config.yaml: |-
    receivers:
      otlp/l2:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.collector.ports.internal.otlpGRPCPort}}

    exporters:
      nop:

      {{ range $name, $flags := .Values.vendors }}
      {{ if and $flags.enabled -}}
      {{ if or $flags.metrics $flags.traces }}
      {{ $flags.exporter }}/{{ $name }}:
        {{ toYaml $flags.config | nindent 8 }}
      {{ end -}}
      {{ end -}}
      {{ end }}

{{ if .Values.s3.enabled }}
      chqs3/l2:
      {{ include "customerside.chqs3.config" . | nindent 8 }}
{{ end }}

    processors:
      # Limit collector process memory usage.  This should be the first processor
      # in the processor list.
      memory_limiter/l2:
        limit_mib: {{ .Values.collector.l2.memory_limiter.limit_mib }}
        spike_limit_mib: {{ .Values.collector.l2.memory_limiter.spike_limit_mib }}
        check_interval: 5s

      batch/intakestats:
        timeout: 1s
        send_batch_size: 100
        send_batch_max_size: 1000

      {{ range $name, $flags := .Values.vendors -}}
      {{ if $flags.enabled -}}
      {{ if or $flags.metrics $flags.traces }}
      batch/{{ $name }}:
        timeout: 1s
        send_batch_size: 100
        send_batch_max_size: 1000
      {{ end -}}
      {{ end -}}
      {{ end -}}

      groupbytrace/l2:
        wait_duration: 60s

      cumulativetodelta/l2:

      chqdecorator/l2:

      chqenforcer/intakestats:
        configuration_extension: chqconfig/cardinalhq
        drop_decoration_attributes: false
        metric_aggregation:
          interval: {{ $.Values.collector.aggregation.interval }}
        statistics:
          endpoint: {{ .Values.collector.endpoints.cardinalhq.stats }}
          auth:
            authenticator: chqauth/cardinalhq
          phase: presample
          vendor: intakestats
        traces:
          uninteresting_rate: 1000
          has_error_rate: 4

      {{ range $name, $flags := .Values.vendors -}}
      {{ if $flags.enabled -}}
      {{ if or $flags.metrics $flags.traces }}
      chqenforcer/{{ $name }}:
        configuration_extension: chqconfig/cardinalhq
        {{ if $flags.keepTags }}
        drop_decoration_attributes: false
        {{ end }}
        metric_aggregation:
          interval: {{ $.Values.collector.aggregation.interval }}
        statistics:
          endpoint: {{ $.Values.collector.endpoints.cardinalhq.stats }}
          auth:
            authenticator: chqauth/cardinalhq
          phase: postsample
          vendor: {{ $name }}
        traces:
          uninteresting_rate: 1000
          has_error_rate: 4
      {{ end -}}
      {{ end -}}
      {{ end }}

    connectors:
      forward/intakestats:
{{ if .Values.s3.enabled }}
      forward/chqs3:
      spanmetrics/l2:
        aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"
        metrics_flush_interval: 10s
        namespace: span.metrics
{{ end }}
      {{ range $name, $flags := .Values.vendors -}}
      {{ if $flags.enabled -}}
      {{ if or $flags.metrics $flags.traces }}
      forward/{{ $name }}:
      {{ end -}}
      {{ end -}}
      {{ end }}

    service:
      pipelines:
        metrics/l2:
          receivers:
            - otlp/l2
          processors:
            - memory_limiter/l2
            - cumulativetodelta/l2
            - chqdecorator/l2
          exporters:
            - forward/intakestats
{{ if .Values.s3.enabled }}
            - forward/chqs3
{{ end }}
            {{ range $name, $flags := .Values.vendors -}}
            {{ if and $flags.enabled $flags.metrics -}}
            - forward/{{ $name }}
            {{ end -}}
            {{ end }}
        metrics/intakestats:
          receivers:
            - forward/intakestats
          processors:
            - chqenforcer/intakestats
          exporters:
            - nop
        {{ range $name, $flags := .Values.vendors }}
        {{ if and $flags.enabled $flags.metrics -}}
        metrics/{{ $name }}:
          receivers:
            - forward/{{ $name }}
          processors:
            - chqenforcer/{{ $name }}
            - batch/{{ $name }}
          exporters:
            - {{ $flags.exporter}}/{{ $name }}
        {{ end -}}
        {{- end -}}

{{ if .Values.s3.enabled }}
        metrics/l2s3:
          receivers:
            - forward/chqs3
          exporters:
            - chqs3/l2

        metrics/spanmetrics:
          receivers:
            - spanmetrics/l2
          processors:
            - chqdecorator/l2
          exporters:
            - forward/chqs3
{{ end }}


        traces/l2:
          receivers:
            - otlp/l2
          processors:
            - memory_limiter/l2
            - groupbytrace/l2
            - chqdecorator/l2
          exporters:
            - forward/intakestats
{{ if .Values.s3.enabled }}
            - spanmetrics/l2
            - chqs3/l2
{{ end }}
            {{ range $name, $flags := .Values.vendors -}}
            {{ if and $flags.enabled $flags.traces -}}
            - forward/{{ $name }}
            {{ end -}}
            {{ end }}

        traces/intakestats:
          receivers:
            - forward/intakestats
          processors:
            - chqenforcer/intakestats
          exporters:
            - nop
        {{ range $name, $flags := .Values.vendors }}
        {{ if and $flags.enabled $flags.traces -}}
        traces/{{ $name }}:
          receivers:
            - forward/{{ $name }}
          processors:
            - chqenforcer/{{ $name }}
            - batch/{{ $name }}
          exporters:
            - {{ $flags.exporter}}/{{ $name }}
        {{ end -}}
        {{- end -}}

      {{ toYaml .Values.selfTelemetry | nindent 6 }}

      extensions:
        - zpages
        - health_check
        - chqauth/cardinalhq
        - chqconfig/cardinalhq
        - file_storage/scratch

    extensions:
      zpages:
        endpoint: "0.0.0.0:{{ .Values.collector.endpoints.zpages.port }}"
      health_check:
        endpoint: "0.0.0.0:{{ .Values.collector.endpoints.healthz.port }}"
        path: {{ .Values.collector.endpoints.healthz.path }}
      chqauth/cardinalhq:
        client_auth:
          api_key: ${env:CARDINALHQ_API_KEY}
          environment:
            collector_id: ${env:CARDINALHQ_COLLECTOR_ID}
            customer_id: ${env:CARDINALHQ_CUSTOMER_ID}
      chqconfig/cardinalhq:
        source:
          endpoint: {{ .Values.collector.endpoints.cardinalhq.samplerConfig }}
          auth:
            authenticator: chqauth/cardinalhq
      file_storage/scratch:
        directory: /app/scratch
