apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "customerside.labels" . | nindent 4 }}
  {{- include "customerside.role.annotations" . | nindent 2 }}
  name: {{ include "customerside.fullname" . }}-loadbalancer
  {{- include "customerside.namespace" . | nindent 2 }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "customerside.labels" . | nindent 4 }}
  {{- include "customerside.roleBinding.annotations" . | nindent 2 }}
  name: {{ include "customerside.fullname" . }}-loadbalancer
  {{- include "customerside.namespace" . | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "customerside.fullname" . }}-loadbalancer
subjects:
- kind: ServiceAccount
  name: {{ include "customerside.fullname" . }}-loadbalancer
