{{ if .Values.chqs3.enabled}}
  # {{ required "A valid s3uploader.region is required!" .Values.chqs3.config.s3uploader.region }}
  # {{ required "A valid s3uploader.bucket is required!" .Values.chqs3.config.s3uploader.s3_bucket }}
{{ end }}

{{ if eq .Values.secrets.create false }}
  # {{ required "A valid cardinalhq secret name is required when create=false!" .Values.secrets.cardinalhq.name }}
  # {{ required "A valid datadog secret name is required when create=false!" .Values.secrets.datadog.name }}
  # {{ required "A valid aws secret name is required when create=false!" .Values.secrets.aws.name }}
{{ end }}
