{{ if .Values.chqs3.enabled}}
  # {{ required "A valid s3uploader.region is required!" .Values.chqs3.config.s3uploader.region }}
  # {{ required "A valid s3uploader.bucket is required!" .Values.chqs3.config.s3uploader.s3_bucket }}
{{ end }}

{{ if eq .Values.secrets.create false }}
  # {{ required "A valid cardinalhq secret name is required when create=false!" .Values.secrets.cardinalhq.name }}
  # {{ required "A valid datadog secret name is required when create=false!" .Values.secrets.datadog.name }}
  # {{ required "A valid aws secret name is required when create=false!" .Values.secrets.aws.name }}
{{ end }}

{{ if .Values.secrets.create }}
  # {{ required "A valid cardinalhq secret apiKey is required when create=true!" .Values.secrets.cardinalhq.apiKey }}
  # {{ required "A valid datadog secret apiKey is required when create=true!" .Values.secrets.datadog.apiKey }}
  # {{ required "A valid aws secret accessKey is required when create=true!" .Values.secrets.aws.accessKey }}
  # {{ required "A valid aws secret secretKey is required when create=true!" .Values.secrets.aws.secretKey }}
{{ end }}
