apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "customerside.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector-l1
  {{- include "customerside.service.annotations" . | nindent 2 }}
  name: {{ include "customerside.fullname" . }}-collector-l1
  {{- include "customerside.namespace" . | nindent 2 }}
spec:
  selector:
    {{- include "customerside.selectorLabels" . | nindent 4}}
    app.kubernetes.io/component: collector-l1
  ports:
    - name: otlp
      port: {{ .Values.collector.ports.incoming.otlpGRPCPort }}
    - name: http
      port: {{ .Values.collector.ports.incoming.otlpHTTPPort }}
    - name: datadog
      port: {{ .Values.collector.ports.incoming.datadogPort }}
