{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "customerside.labels" . | nindent 4 }}
  {{- include "customerside.secret.annotations" . | nindent 2 }}
  name: {{ include "customerside.fullname" . }}-cardinalhq-apikey
  {{- include "customerside.namespace" . | nindent 2 }}
type: Opaque
data:
  api-key: |-
    {{ b64enc .Values.secrets.cardinalhq.apiKey }}
{{- end -}}
