apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "customerside.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector-l1
  {{- include "customerside.deployment.annotations" . | nindent 2 }}
  name: {{ include "customerside.fullname" . }}-collector-l1
  {{- include "customerside.namespace" . | nindent 2 }}
spec:
  replicas: {{ .Values.collector.l1.replicas | default 2 }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "customerside.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: collector-l1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "customerside.labels" . | nindent 8 }}
        app.kubernetes.io/component: collector-l1
    spec:
      serviceAccountName: {{ include "customerside.fullname" . }}-loadbalancer
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
      containers:
        - name: collector
          image: "{{ .Values.collector.l1.image.repository }}:{{ .Values.collector.l1.image.tag }}"
          command:
            - "/app/bin/cardinalhq-otel-collector"
            - "--config=/app/config/config.yaml"
            - "--feature-gates=component.UseLocalHostAsDefaultHost"
          env:
{{- if .Values.collector.l1.env.gomemlimit }}
            - name: GOMEMLIMIT
              value: "{{ .Values.collector.l1.env.gomemlimit }}"
{{- end }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: "Delta"
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cardinal-collector-datadog
                  key: api-key
            - name: CARDINALHQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cardinal-collector-chq
                  key: api-key
          ports:
            - name: http
              containerPort: {{ .Values.collector.ports.incoming.otlpHTTPPort }}
              protocol: TCP
            - name: otlp
              containerPort: {{ .Values.collector.ports.incoming.otlpGRPCPort }}
              protocol: TCP
            - name: zpages
              containerPort: {{ .Values.collector.endpoints.zpages.port }}
              protocol: TCP
            - name: healthz
              containerPort: {{ .Values.collector.endpoints.healthz.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.collector.endpoints.healthz.path }}
              port: {{ .Values.collector.endpoints.healthz.port }}
            initialDelaySeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
{{- if .Values.collector.l1.resources }}
          resources:
{{ toYaml .Values.collector.l1.resources | indent 12 }}
{{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{ include "customerside.fullname" . }}-collector-config-l1
