apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ template "customerside.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: collector-l2
  name: {{ include "customerside.fullname" . }}-collector-l2
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "customerside.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: collector-l2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "customerside.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: collector-l2
    spec:
      serviceAccountName: loadbalancer
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
      containers:
        - name: collector
          image: cardinalhq-otel-collector
          command:
            - "/app/bin/cardinalhq-otel-collector"
            - "--config=/app/config/config.yaml"
            - "--feature-gates=component.UseLocalHostAsDefaultHost"
          env:
            - name: GOMEMLIMIT
              value: "700MiB"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: "Delta"
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cardinal-collector-datadog
                  key: api-key
            - name: CARDINALHQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cardinal-collector-chq
                  key: api-key
          ports:
            - name: otlp2
              containerPort: 14317
              protocol: TCP
            - name: zpages
              containerPort: 55679
              protocol: TCP
            - name: healthz
              containerPort: 13133
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 13133
            initialDelaySeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 850m
              memory: 1000Mi
            requests:
              cpu: 850m
              memory: 1000Mi
          volumeMounts:
            - name: config
              mountPath: /app/config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{ include "customerside.fullname" . }}-collector-config-l2
