apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: {{ template "customerside.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: {{ include "customerside.fullname" . }}-loadbalancer
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "customerside.fullname" . }}-loadbalancer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "customerside.fullname" . }}-loadbalancer
subjects:
- kind: ServiceAccount
  name: {{ include "customerside.fullname" . }}-loadbalancer
