apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: collector
resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - config.yaml
  - rbac.yaml
patchesJson6902:
- patch: |-
    - op: add
      path: /subjects/0/namespace
      value: 
        collector
  target:
    group: rbac.authorization.k8s.io
    kind: RoleBinding
    version: v1
    name: loadbalancer-rolebinding
