apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
  name: cardinal-collector
spec:
  ports:
    # internal port otlp2 should not be in this service, as we don't want to expose it
    # to the outside world.  We only want properly partitioned data to go there.
    - name: otlp
      port: 4317
    - name: http
      port: 4318
  selector:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
  name: cardinal-collector-l2
spec:
  ports:
    - name: otlp2
      port: 14317
  selector:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
  clusterIP: None
