name: Assume AWS Role and Session
description: Assumes an AWS role to go AWS things
inputs:
  role-arn:
    description: Role ARN to assume
    required: true
  aws-region:
      description: Aws region
      required: true
  env:
    description: The environment to start a session in (dev,test, prod, etc)
    required: false
runs:
  using: composite
  steps:
    - name: Assume Cardinal Infra Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        audience: sts.amazonaws.com
        role-to-assume: ${{ role-arn }}
        aws-region: ${{ aws-region }}
        role-session-name: GitHubActions