apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gke-dev-dd
  name: cardinal-collector-config
data:
  config.yaml: |-
    receivers:
      chqdatadog:
        endpoint: 0.0.0.0:8126
    exporters:
      debug:
        verbosity: detailed
        sampling_initial: 10
        sampling_thereafter: 1001
      nop:

    service:
      pipelines:
        logs:
          receivers: [chqdatadog]
          exporters: [nop]
        metrics:
          receivers: [chqdatadog]
          exporters: [nop]
        traces:
          receivers: [chqdatadog]
          exporters: [nop]
      extensions:
        - zpages
        - health_check

      telemetry:
        metrics:
          readers:
            - periodic:
                interval: 10s
                exporter:
                  otlp:
                    protocol: grpc/protobuf
                    endpoint: http://cardinal-collector.collector.svc.cluster.local:4317

    extensions:
      zpages:
        endpoint: "0.0.0.0:55679"
      health_check:
        endpoint: "0.0.0.0:13133"
        path: "/healthz"
