apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gke-dev-dd
  name: cardinal-collector
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: cardinalhq
      app.kubernetes.io/component: collector
      app.kubernetes.io/instance: collector-gke-dev-dd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cardinalhq
        app.kubernetes.io/component: collector
        app.kubernetes.io/instance: collector-gke-dev-dd
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
      containers:
        - name: collector
          image: us-central1-docker.pkg.dev/profound-ship-384422/cardinalhq/cardinalhq-otel-collector:latest
          command:
            - "/app/bin/cardinalhq-otel-collector"
            - "--config=/app/config/config.yaml"
            - "--feature-gates=component.UseLocalHostAsDefaultHost"
          env:
            - name: GOMEMLIMIT
              value: "100MiB"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: "Delta"
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cardinal-collector-datadog
                  key: api-key
          ports:
            - name: datadog
              containerPort: 8126
              protocol: TCP
            - name: zpages
              containerPort: 55679
              protocol: TCP
            - name: healthz
              containerPort: 13133
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 13133
            initialDelaySeconds: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 512m
              memory: 1Gi
            requests:
              cpu: 512m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /app/config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: cardinal-collector-config
