apiVersion: v1
kind: Namespace
metadata:
  name: collector-dev-dd
  labels:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gke-dev-dd
