apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gke-dev-dd
  name: cardinal-collector
spec:
  ports:
    - name: datadog
      port: 8126
  selector:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gke-dev-dd
