apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customerside.fullname" . }}-cardinal-collector
  labels:
    app.kubernetes.io/component: collector
  {{- include "customerside.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cardinalCollector.replicas }}
  revisionHistoryLimit: {{ .Values.cardinalCollector.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/component: collector
      app.kubernetes.io/instance: collector-{{ .Values.kubernetesClusterName }}-customerside
      app.kubernetes.io/name: cardinalhq
    {{- include "customerside.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: collector
        app.kubernetes.io/instance: collector-{{ .Values.kubernetesClusterName }}-customerside
        app.kubernetes.io/name: cardinalhq
      {{- include "customerside.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /app/bin/cardinalhq-otel-collector
        - --config=/app/config/config.yaml
        - --feature-gates=component.UseLocalHostAsDefaultHost
        env:
        - name: GOMEMLIMIT
          value: {{ quote .Values.cardinalCollector.collector.env.gomemlimit }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: {{ quote .Values.cardinalCollector.collector.env.otelExporterOtlpMetricsTemporalityPreference
            }}
        - name: DATADOG_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: cardinal-collector-datadog
        - name: CARDINALHQ_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: cardinal-collector-chq
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.cardinalCollector.collector.image.repository }}:{{ .Values.cardinalCollector.collector.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 13133
          initialDelaySeconds: 3
        name: collector
        ports:
        - containerPort: 4318
          name: http
          protocol: TCP
        - containerPort: 4317
          name: otlp
          protocol: TCP
        - containerPort: 14317
          name: otlp2
          protocol: TCP
        - containerPort: 55679
          name: zpages
          protocol: TCP
        - containerPort: 13133
          name: healthz
          protocol: TCP
        resources: {{- toYaml .Values.cardinalCollector.collector.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.cardinalCollector.collector.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /app/config
          name: config
      restartPolicy: Always
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: {{ include "customerside.fullname" . }}-loadbalancer
      volumes:
      - configMap:
          name: {{ include "customerside.fullname" . }}-config
        name: config