collector:
  ports:
    incoming:
      otlpGRPCPort: 4317
      otlpHTTPPort: 4318
      datadogPort: 8126
    internal:
      otlpGRPCPort: 14317
  endpoints:
    datadog:
      metrics: https://intake.cardinalhq.io
      logs: https://intake.cardinalhq.io
      traces: https://intake.cardinalhq.io
      compression: gzip
    cardinalHQ:
      otlpGRPC: https://chq-collector-grpc.svc.aws.dev.cardinalhq.net:443
      stats: https://stats-receiver.svc.aws.dev.cardinalhq.net
      statsInterval: 30s
      samplerConfig: https://api.svc.aws.dev.cardinalhq.net/api/v1/samplerConfig
    zpages:
      port: 55679
    healthz:
      port: 13133
      path: /healthz
  l1:
    image:
      repository: us-central1-docker.pkg.dev/profound-ship-384422/cardinalhq/cardinalhq-otel-collector
      tag: latest
    replicas: 2
    env:
      gomemlimit: 1500MiB
    resources:
      limits:
        cpu: 2000m
        memory: 2000Mi
      requests:
        cpu: 2000m
        memory: 2000Mi
  l2:
    image:
      repository: us-central1-docker.pkg.dev/profound-ship-384422/cardinalhq/cardinalhq-otel-collector
      tag: latest
    replicas: 2
    env:
      gomemlimit: 700MiB
    resources:
      limits:
        cpu: 850m
        memory: 1000Mi
      requests:
        cpu: 850m
        memory: 1000Mi
loadbalancer:
  serviceName: collector-l2

# Secrets and references.
secrets:
  # If "create" is true, the contents of the "apiKey" field will be used to
  # create a secret with an internally generated name.
  create: true
  cardinalhq:
    # if "create" is false, use this reference.  It is not used if "create" is true.
    name:
    apiKey: dummy-chq-api-key
  datadog:
    # if "create" is false, use this reference.  It is not used if "create" is true.
    name:
    apiKey: dummy-datadog-api-key

# Annotations for various resources.
annotations:
  # common annotations are set on all resources.
  common: {}
  # specific annotations are set on specific resources.
  serviceAccount: {}
  deployment: {}
  pod: {}
  service: {}
  configMap: {}
  secret: {}
  role: {}
  roleBinding: {}
