{
  "logs": {
    "sampling": [
      {
        "id": "rule1",
        "ruleType": "random",
        "sampleRate": 0.25
      }, {
        "id": "rule2",
        "ruleType": "rps",
        "rps": 2,
        "scope": {
          "resource.service.name": "cardinal-receiver"
        }
      }
    ]
  },
  "metrics": {
    "sampling": [
      {
        id: "metricrule1",
        MetricName: "cardinalhq.middleware.compression",
        TagAction: "drop",
        Tags: [
          "metric.content_encoding"
        ]
      }
    ]
  }
}
