#!/bin/sh
# Copyright 2024-2025 CardinalHQ, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Bump the pinned OpenTelemetry version everywhere:
#   ./scripts/bump-otel.sh v0.157.0
# Regenerates cardinalhq-otel-collector.yaml from the upstream otelcol-contrib
# manifest at that tag plus our overlay (manifest-cardinalhq.yaml), bumps the
# Makefile pin and every local go.mod, then tidies.
set -eu

NEW=${1:?usage: $0 vX.Y.Z (e.g. v0.157.0)}
cd "$(dirname "$0")/.."
YAML=cardinalhq-otel-collector.yaml

OLD=$(awk -F= '/^OTEL_VERSION=/{print $2}' Makefile)
# ponytail: stable (v1.x) core modules track the beta (v0.x) minor with a fixed offset of 94
minor() { echo "$1" | cut -d. -f2; }
OLD_STABLE="v1.$(( $(minor "$OLD") - 94 )).0"
NEW_STABLE="v1.$(( $(minor "$NEW") - 94 )).0"
echo "bumping $OLD -> $NEW ($OLD_STABLE -> $NEW_STABLE)"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
curl -fsSL "https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-releases/$NEW/distributions/otelcol-contrib/manifest.yaml" \
  -o "$tmp/upstream.yaml"
sed "s/\${OTEL_VERSION}/$NEW/g" manifest-cardinalhq.yaml > "$tmp/overlay.yaml"

# Merge: upstream sections minus excludes, plus overlay extras. Upstream's
# `replaces` is intentionally dropped (only used for its obi source-tree hack).
sed -n '1,14p' manifest-cardinalhq.yaml > "$YAML" # reuse license header
cat >> "$YAML" <<EOF

# GENERATED by scripts/bump-otel.sh from the upstream otelcol-contrib $NEW
# manifest plus manifest-cardinalhq.yaml. Do not edit; edit the overlay.

EOF
EXCLUDE_RE=$(yq '.exclude | join("|")' "$tmp/overlay.yaml")
export EXCLUDE_RE
yq 'del(.replaces, .dist) | ... comments="" |
    with_entries(.value |= map(select(.gomod | test(strenv(EXCLUDE_RE)) | not)))' \
  "$tmp/upstream.yaml" > "$tmp/base.yaml"
yq 'del(.exclude) | ... comments=""' "$tmp/overlay.yaml" > "$tmp/extras.yaml"
yq eval-all 'select(fi==0) *+ select(fi==1)' "$tmp/base.yaml" "$tmp/extras.yaml" >> "$YAML"

perl -pi -e "s/^OTEL_VERSION=.*/OTEL_VERSION=$NEW/" Makefile

for mod in $(find . -name go.mod -not -path './distribution/*'); do
  dir=$(dirname "$mod")
  echo "==> $dir"
  (
    cd "$dir"
    for m in $(awk -v o="$OLD" -v os="$OLD_STABLE" -v n="$NEW" -v ns="$NEW_STABLE" \
      '$2==o {print $1"@"n} $2==os {print $1"@"ns}' go.mod); do
      go mod edit -require="$m"
    done
    go mod tidy
  )
done
echo "done; now run: make all test"
