apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
  name: cardinal-collector-config
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    exporters:
      datadog/cardinalhq:
        api:
          key: ${env:DATADOG_API_KEY}
        metrics:
          endpoint: https://intake.cardinalhq.io
        logs:
          endpoint: https://intake.cardinalhq.io
        traces:
          endpoint: https://intake.cardinalhq.io
      datadog/actual:
        api:
          site: us3.datadoghq.com
          key: ${env:DATADOG_API_KEY}
    processors:
      batch:
      memory_limiter:
        limit_mib: 400
        spike_limit_mib: 100
        check_interval: 5s
      chqdecorator:
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, chqdecorator, batch]
          exporters: [datadog/cardinalhq]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, chqdecorator, batch]
          exporters: [datadog/cardinalhq, datadog/actual]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, chqdecorator, batch]
          exporters: [datadog/cardinalhq]
    extensions:
      zpages: {}
