apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
  name: cardinal-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cardinalhq
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cardinalhq
        app.kubernetes.io/component: collector
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
      containers:
        - name: collector
          image: us-central1-docker.pkg.dev/profound-ship-384422/cardinalhq/cardinalhq-otel-collector:latest
          command:
            - "/app/bin/cardinalhq-otel-collector"
            - "--config=/app/config/config.yaml"
          env:
            - name: GOMEMLIMIT
              value: "500MiB"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cardinal-collector-datadog
                  key: api-key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cardinal-collector-aws
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cardinal-collector-aws
                  key: secret-access-key
            - name: SAMPLER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cardinal-collector-chq
                  key: api-key
          ports:
            - name: http
              containerPort: 4318
              protocol: TCP
            - name: otlp
              containerPort: 4317
              protocol: TCP
            - name: otlp2
              containerPort: 14317
              protocol: TCP
            - name: zpages
              containerPort: 55679
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 13133
            initialDelaySeconds: 3
            periodSeconds: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 400m
              memory: 600Mi
            requests:
              cpu: 400m
              memory: 600Mi
          volumeMounts:
            - name: config
              mountPath: /app/config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: cardinal-collector-config
