apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
  name: cardinal-collector
spec:
  ports:
    - name: otlp
      port: 4317
    - name: http
      port: 4318
    - name: zpages
      port: 55679
    - name: datadog
      port: 8126
  selector:
    app.kubernetes.io/name: cardinalhq
    app.kubernetes.io/component: collector
