vendors:
  datadog:
    enabled: false

collector:
  l1:
    additionalReceivers:
      - name: kafkametrics
        enabled: true
        logs: false
        metrics: true
        traces: false
        config:
          brokers:
            - kafka:9092
          topic: otel-metrics

chqs3:
  config:
    s3uploader:
      region: us-west-2
      s3_bucket: my-special-bucket
