vendors:
  datadog:
    enabled: false

collector:
  l1:
    additionalReceivers:
      - name: kafkametrics
        enabled: true
        logs: false
        metrics: true
        traces: false
        config:
          config:
            brokers:
              - kafka:9092
            topic: otel-metrics
