name: Build and push to the latest tag to prod
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  
  workflow_dispatch:
    inputs:
      tag-to-deploy:
        description: 'Git tag to build and push (blank to build and tag main)'
        required: false
      should-tag-latest:
        description: 'Tags the resulting docker image latest'
        required: true
        default: true

#registry: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.ECR_REGISTRY_REGION }}.amazonaws.com/
#repository: cardinalhq/tmp-cardinalhq-otel-collector

env:
  registry: public.ecr.aws/cardinalhq.io/
  repository: tmp-cardinalhq-otel-collector
  go-version: '1.22'

jobs:

  build-go-project:
    name: Build Go!
    uses: ./.github/workflows/build-go.yml
    permissions:
      id-token: write
      contents: read
    with:
      tag-to-build: ${{ github.event.inputs.tag-to-deploy || github.ref  }}
      go-version: ${{ env.go-version }}


  release-tag:
    needs: [build-go-project]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      tag: ${{ steps.determine-release-tag.outputs.tag}}
      desc: ${{ steps.determine-release-tag.outputs.desc}}
      today-string: ${{ steps.determine-release-tag.outputs.today-string}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - uses: ./.github/actions/determine-release-tag
        id: determine-release-tag
        with:
          target-tag: ${{ github.event.inputs.tag-to-deploy }}

      - name: Print outputs
        id: print-outputs
        run: |   
          echo "Target tag!: ${{ steps.determine-release-tag.outputs.tag}}"
          echo "Taget tag desc:    ${{ steps.determine-release-tag.outputs.desc}}"
          echo "Hash:   ${{ steps.determine-release-tag.outputs.hash}}"
          echo "Today-string:   ${{ steps.determine-release-tag.outputs.today-string}}"

  build-release-artifacts:
    needs: [ release-tag ]
    if: ${{ needs.release-tag.outputs.tag != '' }}
    name: Build and release images
    uses: ./.github/workflows/docker-build-push-ecr-go.yml
    permissions:
      id-token: write
      contents: read
    with:
      tag-to-release: ${{ needs.release-tag.outputs.tag }}
      registry: ${{ env.registry }}
      repository: ${{ env.repository }}
      should-tag-latest: ${{ github.event.inputs.should-tag-latest }}
    secrets:
      ECR_ACCOUNT_ID: ${{ secrets.ECR_ACCOUNT_ID }}
      ECR_ROLE_NAME: ${{ secrets.ECR_ROLE_NAME }}
      ECR_REGISTRY_REGION: ${{ secrets.ECR_REGISTRY_REGION }}

